@CRM_HostAddress = https://localhost:7273
@AccessToken = your-access-token

### Get customers
GET {{CRM_HostAddress}}/api/customers?page=1&pageSize=10&sortBy=name&sortDirection=desc
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Create customer
POST {{CRM_HostAddress}}/api/customers
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "name": "Alex",
    "email": "alex@test.com"
}

### Get customer by id
GET {{CRM_HostAddress}}/api/customers/1
Authorization: Bearer {{AccessToken}}

### Get Customer orders
GET {{CRM_HostAddress}}/api/customers/1/orders?page=1&pageSize=10&minTotalAmount=0&maxTotalAmount=10&createdFrom=2026-05-01T19:20:06&createdTo=2026-05-18T19:20:06.2885903&sortBy=totalAmount&sortDirection=desc
Authorization: Bearer {{AccessToken}}

### Patch Customer
PATCH {{CRM_HostAddress}}/api/customers/1003
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "email": "alexa@test.com"
}