@CRM_HostAddress = https://localhost:7273
@AccessToken = your-access-token

### Get users
GET {{CRM_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Get user by id
GET {{CRM_HostAddress}}/api/users/1
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Create manager
POST {{CRM_HostAddress}}/api/users/manager
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "name": "Manager 1",
    "email": "manager1@test.com",
    "password": "12345678"
}

### Create admin
POST {{CRM_HostAddress}}/api/users/admin
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
    "name": "Admin 1",
    "email": "admin1@test.com",
    "password": "12345678"
}

### Delete user
DELETE {{CRM_HostAddress}}/api/users/1
Authorization: Bearer {{AccessToken}}